In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random

In [2]:
def GenMatrix(n):
    
    matrix = np.zeros([n,n])

    numOfOnes = int(n**2/2)
    currentOnes = 0
    
    while currentOnes < numOfOnes:
        randrow = random.randint(0, n-1)
        randcol = random.randint(0, n-1)

        if matrix[randrow][randcol] == 0:
            matrix[randrow][randcol] = 1
            currentOnes +=1
    return matrix

In [3]:
def GetWinLoss(n):

    WinLoss = []
    for j in range(0, 100):
        win = 0
        loss = 0
        for i in range(0, 100):
            det = np.linalg.det(GenMatrix(n))

            if det == 0: # Win
                win +=1
            else: # Lose
                loss +=1

        WinLoss.append([win, loss])

    return WinLoss

In [8]:
for n in range(1, 8):
    winloss = GetWinLoss(n)
    winrate = np.mean(winloss, axis=0)
    print("n = " + str(n))
    print(winrate)
    print()

n = 1
[100.   0.]

n = 2
[66.02 33.98]

n = 3
[70.84 29.16]

n = 4
[58.65 41.35]

n = 5
[59.66 40.34]

n = 6
[53.62 46.38]

n = 7
[49.81 50.19]



The winrate when playing at complete random with respect to dimension, starting with dimension n=1: 100, 66.67, 71.5, 58.5, 59.5 54, 49. At n=7, the chances of winning at random are less than 50%.
The way to calculate would be to consider all possible nxn matrices with half the values being 1 and the other half being 0 and getting a more accurate winrate, however I would say this is still relatively accurate up to n=7. 

This strategy, or lack thereof, is good for n<7; and in the case of n=2, if played with strategy is also 100% win. However, this also assumes that player "1" is also playing at random.

If we actually try and consider some strategy, we need some understand some "forcing" cases: conditions, if met, that result in a singular matrix. Some simple cases would be an all zero row or column, this would result in a singular matrix. Another case would be that the matrix is not linearly independent, which is kind of an extension of zero row/column as row/column operations (exculding scaling) do not effect the determinant.

In [40]:
# In the case of n=2
n = 2

matrix = -2*np.ones([n,n]) # Set the matrix essentially blank
print(matrix)
print()

matrix[0][0] = 0 # Set the top left to 0
print(matrix)
print()

matrix[1][0] = 1 # Player "1" has to prevent the column being a 0 column
print(matrix)
print()

matrix[0][1] = 0 # Set the top right to 0
print(matrix)
print()

[[-2. -2.]
 [-2. -2.]]

[[ 0. -2.]
 [-2. -2.]]

[[ 0. -2.]
 [ 1. -2.]]

[[ 0.  0.]
 [ 1. -2.]]



This is a forced case in terms of a 2x2 matrix as player "1" cannot prevent both either the row becoming zero or the column and thus for a 2x2 case, player "0" can always win.

In [48]:
# In the case of n=3
n=3

matrix = -2*np.ones([n,n])

# Suppose we set the middle value to 0 first

matrix[1][1] = 0
print(matrix)
print()

matrix[0][1] = 1
print(matrix)
print()

matrix[1][0] = 0
print(matrix)
print()

matrix[1][2] = 1 # Player "1" is forced to play centre right
print(matrix)
print()

matrix[2][0] = 0
print(matrix)
print()

matrix[0][0] = 1 # Player "1" is forced to play top left
print(matrix)
print()

matrix[2][1] = 0
print(matrix)
print()

matrix[2][2] = 1 # Player "1" is forced to play bottom right
print(matrix)
print()

matrix[0][2] = 0 
print(matrix)
print()

[[-2. -2. -2.]
 [-2.  0. -2.]
 [-2. -2. -2.]]

[[-2.  1. -2.]
 [-2.  0. -2.]
 [-2. -2. -2.]]

[[-2.  1. -2.]
 [ 0.  0. -2.]
 [-2. -2. -2.]]

[[-2.  1. -2.]
 [ 0.  0.  1.]
 [-2. -2. -2.]]

[[-2.  1. -2.]
 [ 0.  0.  1.]
 [ 0. -2. -2.]]

[[ 1.  1. -2.]
 [ 0.  0.  1.]
 [ 0. -2. -2.]]

[[ 1.  1. -2.]
 [ 0.  0.  1.]
 [ 0.  0. -2.]]

[[ 1.  1. -2.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]

[[1. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]



As we can see, this results in a singular matrix and player "1" had to play three forcing moves, with the first move being their choice. I would claim that you could also always win with strategy in a 3x3 matrix.